### ISSUE TITLE
Booting custom kernel

### ISSUE THREAD

**Issue by kristofpetho** [nakixii/android_kernel_oneplus_sm8350#1]
Hey, are you able to boot your kernel on OOS? It builds clean for me without warnings or errors, but I can't get it to boot...

Thanks,

Kristof

**Comment by nakixii** [comment]
I haven't got an OP9Pro yet

**Comment by kristofpetho** [comment]
Oh ok thanks

**Comment by nakixii** [comment]
are you able to boot your kernel now?

**Comment by kristofpetho** [comment]
Yes. But when I inline all modules, the touchscreen is off by about 2-3 mm's.
